JohnRoyCabezas/ps-university-ebulletin-board

client/package-lock.json
client/package.json
client/src/components/Dropdown.js
client/src/components/Navbar.js
client/src/index.css
client/src/pages/RegisterPage.js
client/src/routes/RoutesList.js
client/tailwind.config.js

- https://app.asana.com/0/1203011106874563/1203011106874551/f
Markup:

[008][Markup] Create markup for register page

---

client/package-lock.json
client/package.json
client/src/components/AnnouncementCard.js
client/src/components/Dropdown.js
client/src/components/Navbar.js
client/src/components/Sidebar.js
client/src/index.css
client/src/pages/AnnouncementPage.js
client/src/pages/RegisterPage.js
client/src/routes/RoutesList.js
client/tailwind.config.js

- https://app.asana.com/0/1203011106874563/1203034611151674/f

[014][Markup] Create markup for student dashboard page

---

client/src/api/AuthApi.js
client/src/components/ErrorMessage.js
client/src/pages/LoginPage.js
client/src/routes/RoutesList.js

https://app.asana.com/0/1203011106874563/1203011106874622/f

[010][FE] Integration of LoginPage

---

client/package-lock.json
client/package.json
client/src/pages/LandingPage.js
client/src/routes/RoutesList.js

https://app.asana.com/0/1203011106874563/1203011106874632/f

[001][Markup] Create landing page markup

---

client/src/pages/AdminSettingsPage.js
client/src/routes/RoutesList.js

https://app.asana.com/0/1203011106874563/1203087509751269/f

[020][Markup] Create markup for Admin Settings Page

---

client/src/components/RegistrationModal.js
client/src/pages/RegisterPage.js

https://app.asana.com/0/1203011106874563/1203088964406012

[051][Bugfix] Create modal for Successful User registration

---

client/src/api/AnnouncementApi.js
client/src/api/AuthApi.js
client/src/components/AdminMessageOptions.js
client/src/components/AnnouncementCard.js
client/src/components/DeleteModal.js
client/src/components/RichTextEditor.js
client/src/components/StudentMessageOptions.js
client/src/pages/AdminAnnouncementPage.js
client/src/pages/AnnouncementPage.js

https://app.asana.com/0/1203011106874563/1203034611151678/f

[019][FE] Integration of announcement page (admin view)

---

api/app/Http/Controllers/AuthController.php
api/app/Models/College.php
api/app/Models/User.php
api/routes/api.php
client/src/api/AuthApi.js
client/src/components/SideBarPopup.js
client/src/pages/AnnouncementPage.js
client/src/pages/LandingPage.js
client/src/pages/LoginPage.js
client/src/routes/RoutesList.js

https://app.asana.com/0/1203011106874563/1203112124151448

[052][FE]-001 Setup Auth routes

---

api/app/Http/Controllers/AuthController.php
api/app/Models/Announcement.php
api/app/Models/User.php
api/database/migrations/2022_09_23_101906_create_users_table.php

https://app.asana.com/0/1203011106874563/1203087509751276
* Testing User Update:
* Testing User soft Delete: 
* Update User
* Delete User

[023][BE] Add function to delete update and destroy user information in AuthController

---

client/src/components/SideBarPopup.js
client/src/pages/ErrorPage.js
client/src/pages/LandingPage.js
client/src/pages/LoginPage.js
client/src/pages/Unauthorized.js
client/src/routes/RoutesList.js
client/src/routes/utilities/ProtectedRoute.js

https://app.asana.com/0/1203011106874563/1203120409302779
* Upon login, user should be redirected to AnnouncementPage
* The announcements should be available without the need to refresh the page
* User should be redirected to unauthorized page when he tries to change the URL to visit the admin-authorized-only pages

[053][FE] Setup Protected Routes for Student and Admin

---

client/src/components/Paginate.js
client/src/components/RegistrationModal.js
client/src/components/UsersTable.js
client/src/pages/ManageUsersPage.js
client/src/pages/RegisterPage.js
client/src/routes/RoutesList.js

https://app.asana.com/0/1203011106874563/1203087509751270/f

[022][Markup] Create markup for Manage Users Page

---

client/src/pages/EditCollegePage.js
client/src/routes/RoutesList.js

https://app.asana.com/0/1203011106874563/1203087509751343/f

[040][Markup] Create markup for Edit College page

---

api/app/Http/Controllers/UserController.php
api/routes/api.php
client/src/api/CollegeApi.js
client/src/api/UserApi.js
client/src/components/Dropdown.js
client/src/components/SuccessModal.js
client/src/pages/AdminSettingsPage.js
client/src/pages/CreateCollegePage.js

[[030][FE] Integrate backend api for creating a college](https://app.asana.com/0/1203011106874563/1203087509751299)
* Creating a college
Without creating a new user with role:admin, there will only be one a available option under the College Dean dropdown.

[030][FE] Integrate backend api for creating a college

---

api/app/Http/Controllers/DepartmentController.php
api/app/Models/Department.php
api/database/migrations/2022_10_10_105537_add_column_to_departments_table.php

https://app.asana.com/0/1203011106874563/1203087509751291/f
`http://127.0.0.1:8000/api/department?college_id=1&user_id=2&department=Sample Engineering&department_information=Sample Engineering Information` to create a department. PS: Set the method to **POST**
`http://127.0.0.1:8000/api/department/15?college_id=1&user_id=2&department=Sample update Engineering&department_information=Sample update Engineering Information` to update a department. PS: Set the method to **PUT**

[026][BE] Creation of DepartmentController

---

api/app/Http/Controllers/AuthController.php
api/app/Http/Controllers/CourseController.php
api/app/Models/Course.php
api/app/Models/CourseUser.php
api/database/migrations/2022_09_26_015318_create_course_users_table.php
api/database/seeders/DatabaseSeeder.php
api/routes/api.php

https://app.asana.com/0/1203011106874563/1203087509751307/f
`http://127.0.0.1:8000/api/course?course=EE 131&department=Electrical Engineering&user_ids=3,4,5,6` to create a class. PS: Set the method to **POST**
`http://127.0.0.1:8000/api/course/8?course=EE 131 - Updated&department=Computer Engineering&user_ids=3,4,5` to update a class. PS: Set the method to **PUT**

[032][BE] Creation of ClassController

---

api/app/Http/Controllers/AuthController.php
client/src/api/AuthApi.js
client/src/components/SideBarPopup.js
client/src/components/Sidebar.js
client/src/components/UsersTable.js
client/src/pages/EditUserPage.js
client/src/pages/ManageUsersPage.js
client/src/routes/RoutesList.js

https://app.asana.com/0/1203011106874563/1203140685802510
- setup Database and run DatabaseSeeders to create an Admin 
* Update User Info
* SoftDelete User

[058][FE] Integrate update and delete user in ManageUsersPage

---

api/app/Http/Controllers/CollegeContoller.php
api/app/Http/Controllers/UserController.php
api/app/Models/College.php
api/app/Models/RoleUser.php
api/app/Models/University.php
api/app/Models/User.php
api/database/seeders/DatabaseSeeder.php
api/routes/api.php
client/src/api/CollegeApi.js
client/src/api/UserApi.js
client/src/components/DeleteModal.js
client/src/components/SuccessModal.js
client/src/index.js
client/src/pages/CreateCollegePage.js
client/src/pages/EditCollegePage.js

[https://app.asana.com/0/1203011106874563/1203087509751307/f](https://app.asana.com/0/1203011106874563/1203087509751345/f)
-  [ ] Check .env files for api and client directory
-  [ ] Setup postgres environment
-  [ ] Existing registered users with the "Dean" role
-  [ ] Set the const id = {pre existing id inside colleges table} inside the EditCollegePage.js
-  [ ] in the terminal, go to the project directory and cd into api directory - `cd api`
-  [ ] `run php artisan serve`
-  [ ] open another terminal, got to the project directory and cd into client directory - `cd client`
-  [ ] `run npm start`

[044][FE] Integration of Update/Delete EditCollegePage

---

api/app/Http/Controllers/AnnouncementController.php
api/app/Http/Controllers/CollegeController.php
api/app/Models/Announcement.php
api/routes/api.php
client/src/api/AnnouncementApi.js
client/src/components/AnnouncementCard.js
client/src/components/CollegeAccordion.js
client/src/components/SideBarPopup.js
client/src/components/Sidebar.js
client/src/pages/AdminCollegePage.js
client/src/pages/CollegePage.js
client/src/routes/RoutesList.js

https://app.asana.com/0/1203011106874563/1203087509751340/f
https://app.asana.com/0/1203011106874563/1203087509751338/f
Admin college:
college:

[036][037]-001-College Announcement Page

---

client/src/api/CollegeApi.js
client/src/api/DepartmentApi.js
client/src/pages/CreateDepartmentPage.js

https://app.asana.com/0/1203011106874563/1203087509751293/f

[027][FE] Integrate backend api for creating a department

---

api/app/Http/Controllers/AuthController.php
api/app/Http/Controllers/CourseController.php
api/app/Http/Controllers/UserController.php
api/app/Models/CourseUser.php
api/app/Models/User.php
api/database/seeders/DatabaseSeeder.php
api/routes/api.php
client/src/api/CourseApi.js
client/src/api/UserApi.js
client/src/components/DepartmentAccordion.js
client/src/components/Dropdown.js
client/src/components/DropdownMulti.js
client/src/components/SideBarPopupAdmin.js
client/src/components/Sidebar.js
client/src/components/SidebarPopupUser.js
client/src/pages/AdminAnnouncementPage.js
client/src/pages/AnnouncementPage.js
client/src/pages/CollegePage.js
client/src/pages/CreateClassPage.js
client/src/pages/CreateCollegePage.js
client/src/pages/EditUserPage.js
client/src/pages/RegisterPage.js
client/src/routes/RoutesList.js

https://app.asana.com/0/1203011106874563/1203087509751311
* Create Instructors and Students
* Test creating a class

[033][FE] Integrate backend api for creating a class and adding students

---

client/src/pages/AdminSettingsPage.js

https://app.asana.com/0/1203011106874563/1203212539691345

[008][MU] Update Admin settings buttons centered and style button

---

client/src/components/RichTextEditor.js
client/src/pages/AdminAnnouncementPage.js

…nt is empty
https://app.asana.com/0/1203002524654351/1203204651859785/f

[003][009][Bugfix] Disable send button if RichTextEditor in Announcement is empty / Loading animation

---

client/src/components/CollegeAccordion.js
client/src/components/DepartmentAccordion.js
client/src/shared/CollegeIcon.js

https://app.asana.com/0/1203011106874563/1203212539691353
* login as Admin and check the sidebar

[011][Bugfix] Change dropdown of departments under college into a modal

---

api/app/Http/Controllers/DepartmentController.php
client/src/components/CollegeAccordion.js
client/src/components/Sidebar.js
client/src/components/SuccessModal.js
client/src/pages/AdminAnnouncementPage.js
client/src/routes/RoutesList.js

https://app.asana.com/0/1203011106874563/1203212539691335

[004][Bugfix] Update sidebar to remove bugs

---

client/src/components/AnnouncementCard.js
client/src/components/ChatCard.js
client/src/pages/AdminCollegePage.js
client/src/pages/ClassPage.js
client/src/pages/CollegePage.js
client/src/routes/RoutesList.js
client/src/shared/json/Chats.js

https://app.asana.com/0/1203011106874563/1203214619102917
* Login as admin/user and type the URL pathname `.../class`

[065][Markup] Create markup for class page

---

client/src/api/AnnouncementApi.js
client/src/components/AnnouncementCard.js
client/src/components/Thread.js
client/src/pages/AdminAnnouncementPage.js
client/src/pages/AnnouncementPage.js

https://app.asana.com/0/1203011106874563/1203087509751382/f
As Admin
As normal user

[050][FE] Integrate thread locking of announcements

---

client/src/components/UsersTable.js
client/src/pages/ManageUsersPage.js

https://app.asana.com/0/1203011106874563/1203212539691339

[006] Make UI smaller for ManageUsers Page and add more items per page

---

api/app/Http/Controllers/UniversityController.php
api/app/Models/University.php
api/routes/api.php

https://app.asana.com/0/1203011106874563/1203204651447825/f

[062][BE] Created Controller for creating university

---

client/src/components/AnnouncementCard.js

https://app.asana.com/0/1203011106874563/1203212539691349

[010] Update width of RichTextEditor to w-full

---

client/src/components/RichTextEditor.js
client/src/components/submitButton.js
client/src/pages/AdminAnnouncementPage.js
client/src/pages/AdminSettingsPage.js
client/src/pages/AnnouncementPage.js
client/src/pages/CreateClassPage.js
client/src/pages/CreateCollegePage.js
client/src/pages/CreateDepartmentPage.js
client/src/pages/EditCollegePage.js
client/src/pages/RegisterPage.js

https://app.asana.com/0/1203002524654351/1203240570339880/f

[001][Hotfix] Submit button Integration

---

api/app/Http/Controllers/ThreadController.php
api/app/Models/Announcement.php
api/app/Models/Thread.php
api/routes/api.php
client/src/components/RichTextEditor.js

https://app.asana.com/0/1203011106874563/1203087509751325/f

[046][BE] Create ThreadController with thread functions

---

api/app/Http/Controllers/ChatController.php
api/app/Http/Controllers/CourseController.php
api/app/Http/Controllers/UserController.php
api/app/Models/Chat.php
api/app/Models/Course.php
api/app/Models/CourseUser.php
api/app/Models/User.php
api/database/migrations/2022_10_26_023543_create_chats_table.php
api/routes/api.php
client/src/api/ChatApi.js
client/src/api/CourseApi.js
client/src/components/ChatCard.js
client/src/components/ChatOptions.js
client/src/components/ChatTextEditor.js
client/src/components/CollegeAccordion.js
client/src/components/Course.js
client/src/components/DepartmentAccordion.js
client/src/components/Sidebar.js
client/src/pages/AdminCollegePage.js
client/src/pages/AdminDepartmentPage.js
client/src/pages/ClassPage.js
client/src/pages/CollegePage.js
client/src/pages/DepartmentPage.js
client/src/routes/RoutesList.js

https://app.asana.com/0/1203011106874563/1203214619102920
https://app.asana.com/0/1203011106874563/1203212539691329
https://app.asana.com/0/1203011106874563/1203212539691331
https://app.asana.com/0/1203011106874563/1203214619102919
This PR covers multiple Asana tasks under Class. Reason for compiling all tasks into one PR is to fulfill the entire feature for ClassPage instead of breaking it down into multiple small tasks which would required a waiting time for PR approval.
* Navigate to the classroom (as Admin/Student)
* Creating a chat message
* Editing a chat message
* Deleting a chat message

[078][FE] Integrate ClassPage features

---

api/app/Http/Controllers/CollegeController.php
client/src/api/CollegeApi.js
client/src/pages/CreateCollegePage.js

https://app.asana.com/0/1203002524654351/1203248090179130/f

[014][Bugfix] Dynamic university_id upon creating college

---

api/app/Http/Controllers/ThreadController.php
client/src/api/ThreadApi.js
client/src/components/RichTextEditor.js
client/src/components/Thread.js
client/src/components/ThreadCard.js
client/src/pages/DepartmentPage.js

https://app.asana.com/0/1203011106874563/1203087509751342/f
https://app.asana.com/0/1203011106874563/1203204651859759/f
https://app.asana.com/0/1203011106874563/1203204651859758/f
**University Announcements**
**Department Announcements**

[035][FE] Integrate backend api for fetching announcement threads

---

client/src/api/DepartmentApi.js
client/src/pages/AdminDepartmentPage.js

…n Department page
https://app.asana.com/0/1203011106874563/1203240480059537/f
https://app.asana.com/0/1203011106874563/1203204651859764/f

[072][FE] Integration of announcement fetching on admin department  page

---

api/app/Http/Controllers/AuthController.php
api/app/Http/Controllers/CollegeController.php
api/app/Http/Controllers/DepartmentController.php
api/app/Http/Controllers/UserController.php
api/app/Models/RoleUser.php
api/database/migrations/2022_09_23_101906_create_users_table.php
api/database/seeders/DatabaseSeeder.php
client/src/api/CollegeApi.js
client/src/api/DepartmentApi.js
client/src/api/UserApi.js
client/src/components/SideBarPopupAdmin.js
client/src/components/Sidebar.js
client/src/components/UsersTable.js
client/src/pages/CreateClassPage.js
client/src/pages/CreateCollegePage.js
client/src/pages/CreateDepartmentPage.js
client/src/pages/EditUserPage.js
client/src/pages/RegisterPage.js

https://app.asana.com/0/1203002524654351/1203254953444099/f
- Create new users (instructors, students, deans)
- Login as an admin
- Manage Users Page
- Create College Page
- Create Department Page
- Create Class Page

[015][Bugfix] Users, colleges and departments fetch according to university

---

api/app/Events/ChatUpdate.php
api/app/Http/Controllers/AuthController.php
api/app/Http/Controllers/ChatController.php
api/composer.json
api/composer.lock
api/config/app.php
client/package-lock.json
client/package.json
client/src/components/ChatTextEditor.js
client/src/pages/ClassPage.js

https://app.asana.com/0/1203011106874563/1203258237721039
* A class under College>Department should already be existing and has the Student enrolled
* Backend setup
```
BROADCAST_DRIVER=pusher
PUSHER_APP_ID=1497998
PUSHER_APP_KEY=6d32a294e8e6b327e3c5
PUSHER_APP_SECRET=0bf7cf6b07f0426c4263
PUSHER_HOST=
PUSHER_PORT=443
PUSHER_SCHEME=https
PUSHER_APP_CLUSTER=ap1
```
* Frontend setup
```
REACT_APP_SERVER_API=http://127.0.0.1:8000
app_id = "1497998"
key = "6d32a294e8e6b327e3c5"
secret = "0bf7cf6b07f0426c4263"
cluster = "ap1"
```
* Backend
* Frontend
* Realtime chat

[078][Bugfix] Make chat feature realtime with Pusher

---

api/app/Http/Controllers/UniversityController.php
api/app/Models/University.php
api/routes/api.php
client/src/api/UniversityApi.js
client/src/pages/CreateUniversityPage.js
client/src/pages/LandingPage.js
client/src/routes/RoutesList.js

https://app.asana.com/0/1203011106874563/1203204651447824
https://app.asana.com/0/1203011106874563/1203204651447827
https://app.asana.com/0/1203011106874563/1203204651447826

[064][FE] Integrate creating University in landing page

---

api/app/Http/Controllers/ChatController.php
api/app/Http/Controllers/CommentController.php
api/app/Models/Chat.php
api/app/Models/Comment.php
api/app/Models/User.php
api/database/migrations/2022_11_02_033846_create_comments_table.php
api/database/seeders/DatabaseSeeder.php
api/routes/api.php
client/src/api/CommentApi.js
client/src/components/AdminThreadOptions.js
client/src/components/ChatCard.js
client/src/components/ChatOptions.js
client/src/components/CommentCard.js
client/src/components/CommentOptions.js
client/src/components/CommentTextEditor.js
client/src/components/Comments.js
client/src/components/CommentsHeader.js
client/src/pages/ClassPage.js

https://app.asana.com/0/1203011106874563/1203214619102916
https://app.asana.com/0/1203011106874563/1203204651859795
* API
* CLIENT
* Chat Comments

[069][FE] Fetch chat comments and add edit and delete functionality

---

client/public/index.html
client/src/components/AnnouncementCard.js
client/src/components/RichTextEditor.js
client/src/components/SideBarPopupAdmin.js
client/src/components/Sidebar.js
client/src/components/SidebarPopupUser.js
client/src/components/ThreadCard.js
client/src/index.css
client/src/pages/AdminAnnouncementPage.js
client/src/pages/AdminDepartmentPage.js
client/src/pages/ClassPage.js

https://app.asana.com/0/1203002524654351/1203254953444101/f

[016][Bugfix] Styles from RichTextEditor now properly renders

---

api/app/Events/AnnouncementUpdate.php
api/app/Http/Controllers/AnnouncementController.php
api/app/Http/Controllers/ChatController.php
client/src/pages/AdminAnnouncementPage.js
client/src/pages/AnnouncementPage.js
client/src/pages/ClassPage.js

https://app.asana.com/0/1203011106874563/1203204651859771
* Announcements
Note: The code behind new Chat Events were also updated. The event is fired upon creating a new chat message in the ClassPage.

[060][BE/FE] Make announcements in AnnouncementPage autoupdate in realtime
